/** Mirrors Android [FirebaseCollections]. */
export const ENTITY_SNAPSHOT_DOC_ID = 'latest';
export const SHARED_FARM_DOCUMENT_ID = 'farm';

export const COLLECTIONS = {
  APP_STATE: 'app_state',
  USER_DATA: 'user_data',
  USERS: 'users',
  PASSWORD_RESET_REQUESTS: 'password_reset_requests',
  WORKERS: 'workers',
  ATTENDANCE: 'attendance',
  TIMESHEET_CORRECTIONS: 'timesheet_corrections',
  LEAVE_REQUESTS: 'leave_requests',
  TASKS: 'tasks',
  FARM_SECTIONS: 'farm_sections',
  TREES: 'trees',
  TREE_RIPENESS_SCANS: 'tree_ripeness_scans',
  HARVEST_SCHEDULES: 'harvest_schedules',
  HARVEST_READINESS_REPORTS: 'harvest_readiness_reports',
  FLOWERING: 'flowering',
  HARVEST_RECORDS: 'harvest_records',
  BATCHES: 'batches',
  CNN_CLASSIFICATIONS: 'cnn_classifications',
  EQUIPMENT: 'equipment',
  EQUIPMENT_USAGE: 'equipment_usage',
  MAINTENANCE_LOGS: 'maintenance_logs',
  EQUIPMENT_REPORTS: 'equipment_reports',
  SALES: 'sales',
  EXPENSES: 'expenses',
  PAYROLL: 'payroll',
  COFFEE_FIELDS: 'coffee_fields',
  IRRIGATION_SYSTEMS: 'irrigation_systems',
  IRRIGATION_DAMAGE_REPORTS: 'irrigation_damage_reports',
  PEST_CONTROL_LOGS: 'pest_control_logs',
  CONSUMABLE_SUPPLIES: 'consumable_supplies',
  CONSUMABLE_REPORTS: 'consumable_reports',
  SMS_MESSAGES: 'sms_messages',
} as const;

export const MIRROR_COLLECTIONS: { key: string; name: string }[] = [
  { key: 'workers', name: COLLECTIONS.WORKERS },
  { key: 'attendance', name: COLLECTIONS.ATTENDANCE },
  { key: 'timesheetCorrections', name: COLLECTIONS.TIMESHEET_CORRECTIONS },
  { key: 'leaveRequests', name: COLLECTIONS.LEAVE_REQUESTS },
  { key: 'tasks', name: COLLECTIONS.TASKS },
  { key: 'sections', name: COLLECTIONS.FARM_SECTIONS },
  { key: 'trees', name: COLLECTIONS.TREES },
  { key: 'treeRipenessScans', name: COLLECTIONS.TREE_RIPENESS_SCANS },
  { key: 'harvestSchedules', name: COLLECTIONS.HARVEST_SCHEDULES },
  { key: 'harvestReadinessReports', name: COLLECTIONS.HARVEST_READINESS_REPORTS },
  { key: 'flowering', name: COLLECTIONS.FLOWERING },
  { key: 'cherryHarvests', name: COLLECTIONS.HARVEST_RECORDS },
  { key: 'batches', name: COLLECTIONS.BATCHES },
  { key: 'cherryGrades', name: COLLECTIONS.CNN_CLASSIFICATIONS },
  { key: 'equipment', name: COLLECTIONS.EQUIPMENT },
  { key: 'usageLogs', name: COLLECTIONS.EQUIPMENT_USAGE },
  { key: 'maintenanceLogs', name: COLLECTIONS.MAINTENANCE_LOGS },
  { key: 'equipmentReports', name: COLLECTIONS.EQUIPMENT_REPORTS },
  { key: 'sales', name: COLLECTIONS.SALES },
  { key: 'expenses', name: COLLECTIONS.EXPENSES },
  { key: 'payroll', name: COLLECTIONS.PAYROLL },
  { key: 'coffeeFields', name: COLLECTIONS.COFFEE_FIELDS },
  { key: 'irrigationSystems', name: COLLECTIONS.IRRIGATION_SYSTEMS },
  { key: 'irrigationDamageReports', name: COLLECTIONS.IRRIGATION_DAMAGE_REPORTS },
  { key: 'pestControlLogs', name: COLLECTIONS.PEST_CONTROL_LOGS },
  { key: 'consumableSupplies', name: COLLECTIONS.CONSUMABLE_SUPPLIES },
  { key: 'consumableReports', name: COLLECTIONS.CONSUMABLE_REPORTS },
  { key: 'smsMessages', name: COLLECTIONS.SMS_MESSAGES },
];
